name: Test Deployment Guard
on: { workflow_dispatch: {} }

jobs:
  gate:
    runs-on: ubuntu-latest
    outputs:
      allow: ${{ steps.gate.outputs.allow }}
    steps:
      - id: gate
        shell: bash
        run: |
          val="${{ vars.allow_deployment }}"
          val="${val,,}"  # lowercase in bash
          if [[ -z "$val" || "$val" == "true" ]]; then
            echo "allow=true" >> "$GITHUB_OUTPUT"
          else
            echo "allow=false" >> "$GITHUB_OUTPUT"
          fi

  guarded-job:
    needs: gate
    if: ${{ needs.gate.outputs.allow == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "✅ Deployment allowed (missing or true)"

  blocked-job:
    needs: gate
    if: ${{ needs.gate.outputs.allow != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "🚫 Deployment blocked (allow_deployment=${{ vars.allow_deployment }})"
