name: Test Guard Usage

on:
  workflow_dispatch:

jobs:
  guard:
    uses: MM-DevTests/SharedRepo/.github/workflows/deployment_guard.yml@main

  test:
    needs: guard
    runs-on: ubuntu-latest
    if: ${{ needs.guard.outputs.allow == 'true' }}
    steps:
      - run: echo "✅ Guard passed, running tests..."

  skipped-test:
    needs: guard
    runs-on: ubuntu-latest
    if: ${{ needs.guard.outputs.allow != 'true' }}
    steps:
      - run: echo "🚫 Guard blocked, tests skipped."
