name: Deployment Workflow

on:
  workflow_dispatch:

jobs:
  guard:
    uses: MM-DevTests/SharedRepo/.github/workflows/deployment_guard.yml@main

  deploy_a:
    needs: guard
    runs-on: ubuntu-latest
    if: ${{ needs.guard.outputs.allow == 'true' }}
    steps:
      - name: Deploy Application A
        run: |
          echo "🚀 Deployment A running..."
          # Insert deployment A steps here

  deploy_b:
    needs: guard
    runs-on: ubuntu-latest
    if: ${{ needs.guard.outputs.allow == 'true' }}
    steps:
      - name: Deploy Application B
        run: |
          echo "🚀 Deployment B running..."
          # Insert deployment B steps here

  blocked:
    needs: guard
    runs-on: ubuntu-latest
    steps:
      - name: Deployment Blocked
        run: |
          echo "🚫 Deployment blocked by system administrator."
